#!/usr/bin/env python3
"""Regenerate native/src/gli_dispatch.inc from the macOS SDK's OpenGL headers.

Plants vs. Zombies is built with <OpenGL/CGLMacro.h>, which turns every GL call
into a direct call through the current CGL context's function-pointer table
rather than through the gl* entry points, so the game imports no GL symbols at
all.  To serve those calls the runtime has to hand the game a CGL context whose
dispatch table it can read, which means knowing which GL entry point sits at
each slot.

Two SDK headers say exactly that: gliDispatch.h declares the table's members in
order, and CGLMacro.h maps each gl* name onto one of them.  Combining the two
gives slot -> gl* name.  The result is written into the repository so the build
does not depend on parsing SDK headers; rerun this when a new GL entry point is
needed.
"""

import pathlib
import re
import subprocess
import sys

root = pathlib.Path(__file__).resolve().parent.parent
sdk = pathlib.Path(subprocess.run(['xcrun', '--show-sdk-path'],
                                  capture_output=True, text=True,
                                  check=True).stdout.strip())
headers = sdk / 'System/Library/Frameworks/OpenGL.framework/Headers'
dispatch_header = headers / 'gliDispatch.h'
macro_header = headers / 'CGLMacro.h'
for header in (dispatch_header, macro_header):
    if not header.is_file():
        raise SystemExit(f'{header} not found; install the Command Line Tools')

# Ordered dispatch members: the struct's declaration order is the ABI.
text = dispatch_header.read_text()
body = text[text.index('typedef struct __GLIFunctionDispatchRec'):]
body = body[:body.index('} GLIFunctionDispatch')]
members = re.findall(r'\(\*\s*(\w+)\s*\)\s*\(', body)
if not members:
    raise SystemExit('could not read the dispatch members from gliDispatch.h')

# CGLMacro.h: "#define glFoo(...) \\\n\t(*(ctx)->disp.foo)(renderer, ...)".
# The definition wraps onto a continuation line, so join those first.
macros = macro_header.read_text().replace('\\\n', ' ')
entry_for_member = {}
for match in re.finditer(r'#define\s+(gl\w+)\s*\([^)]*\)\s*\(\*\([^)]*\)->disp\.(\w+)\)',
                         macros):
    entry_for_member.setdefault(match.group(2), match.group(1))

names = [entry_for_member.get(member) for member in members]
mapped = sum(1 for name in names if name)

lines = [
    '/*',
    ' * Which GL entry point sits at each slot of a CGL context\'s function',
    ' * dispatch table, for the titles that call GL through <OpenGL/CGLMacro.h>',
    ' * instead of the gl* entry points (Plants vs. Zombies does).  A NULL slot',
    ' * is one CGLMacro.h never names, so no game can reach it through the',
    ' * macro.  Generated by tools/gen_gli_dispatch.py from the SDK\'s',
    ' * gliDispatch.h and CGLMacro.h; do not edit by hand.',
    ' *',
    ' * The context itself is { GLIContext rend; GLIFunctionDispatch disp; ... },',
    ' * so slot i lives at context offset 4 + 4 * i, and every entry takes the',
    ' * renderer as an extra first argument.',
    ' */',
    '',
    f'enum {{ kGliDispatchSlots = {len(members)} }};',
    '',
    'static const char *const kGliDispatchNames[kGliDispatchSlots] = {',
]
for index, name in enumerate(names):
    if name:
        lines.append(f'    [{index}] = "_{name}",')
lines.append('};')
lines.append('')

output = root / 'native/src/gli_dispatch.inc'
output.write_text('\n'.join(lines))
print(f'{output}: {len(members)} slots, {mapped} named by CGLMacro.h')
