#!/usr/bin/env python3
"""Assemble native/src/native_stubs.s (i386) and emit native/src/native_stubs.inc:
a table mapping import names to machine-code byte arrays.  Run after editing the .s file."""
import pathlib, re, subprocess, sys, tempfile
root = pathlib.Path(__file__).resolve().parent.parent
src = root / 'native/src/native_stubs.s'
out = root / 'native/src/native_stubs.inc'
# import name(s) -> stub symbol
BINDINGS = {
    '___toupper': 'toupper', '_toupper': 'toupper', '___tolower': 'tolower', '_tolower': 'tolower',
    '_strlen': 'strlen', '_wcslen': 'wcslen', '_strcmp': 'strcmp', '_wcscmp': 'wcscmp', '_strcasecmp': 'strcasecmp',
    '_memcmp': 'memcmp', '_memchr': 'memchr', '_memcpy': 'memcpy', '___memcpy_chk': 'memcpy',
    '_memmove': 'memmove', '_memset': 'memset', '___memset_chk': 'memset',
    '_floorf': 'floorf', '_ceilf': 'ceilf', '_floor': 'floor', '_ceil': 'ceil',
    '_sqrtf': 'sqrtf', '_sqrt': 'sqrt', '_sinf': 'sinf', '_cosf': 'cosf', '_sin': 'sin', '_cos': 'cos',
    '_OSSpinLockTry': 'OSSpinLockTry', '_OSSpinLockLock': 'OSSpinLockLock', '_OSSpinLockUnlock': 'OSSpinLockUnlock',
    '_OSAtomicAdd32': 'OSAtomicAdd32', '_OSAtomicAdd32Barrier': 'OSAtomicAdd32',
    '_OSAtomicCompareAndSwap32': 'OSAtomicCompareAndSwap32', '_OSAtomicCompareAndSwap32Barrier': 'OSAtomicCompareAndSwap32',
    '_OSAtomicOr32': 'OSAtomicOr32', '_OSAtomicOr32Barrier': 'OSAtomicOr32',
    '__ZSt18_Rb_tree_incrementPSt18_Rb_tree_node_base': 'rb_tree_increment',
    '__ZSt18_Rb_tree_incrementPKSt18_Rb_tree_node_base': 'rb_tree_increment',
    '__ZSt18_Rb_tree_decrementPSt18_Rb_tree_node_base': 'rb_tree_decrement',
    '__ZSt18_Rb_tree_decrementPKSt18_Rb_tree_node_base': 'rb_tree_decrement',
    # std::string (COW)
    '__ZNKSs6lengthEv': 'string_length', '__ZNKSs4sizeEv': 'string_length',
    '__ZNKSs5c_strEv': 'string_data', '__ZNKSs4dataEv': 'string_data', '__ZNKSs5beginEv': 'string_data', '__ZNSs5beginEv': 'string_data',
    '__ZNKSs5emptyEv': 'string_empty', '__ZNKSsixEm': 'string_index', '__ZNSsixEm': 'string_index',
    '__ZNKSs3endEv': 'string_end', '__ZNSs3endEv': 'string_end', '__ZNKSs7compareERKSs': 'string_compare',
    # std::wstring (COW)
    '__ZNKSbIwSt11char_traitsIwESaIwEE6lengthEv': 'string_length', '__ZNKSbIwSt11char_traitsIwESaIwEE4sizeEv': 'string_length',
    '__ZNKSbIwSt11char_traitsIwESaIwEE5c_strEv': 'string_data', '__ZNKSbIwSt11char_traitsIwESaIwEE4dataEv': 'string_data',
    '__ZNKSbIwSt11char_traitsIwESaIwEE5beginEv': 'string_data', '__ZNSbIwSt11char_traitsIwESaIwEE5beginEv': 'string_data',
    '__ZNKSbIwSt11char_traitsIwESaIwEE5emptyEv': 'string_empty',
    '__ZNKSbIwSt11char_traitsIwESaIwEEixEm': 'wstring_index', '__ZNSbIwSt11char_traitsIwESaIwEEixEm': 'wstring_index',
    '__ZNKSbIwSt11char_traitsIwESaIwEE3endEv': 'wstring_end', '__ZNSbIwSt11char_traitsIwESaIwEE3endEv': 'wstring_end',
    '__ZNKSbIwSt11char_traitsIwESaIwEE7compareERKS2_': 'wstring_compare',
}
with tempfile.TemporaryDirectory() as tmp:
    obj = pathlib.Path(tmp) / 'stubs.o'
    subprocess.run(['clang', '-target', 'i386-apple-macosx10.13', '-x', 'assembler', '-c', str(src), '-o', str(obj)], check=True)
    syms = []
    for line in subprocess.run(['nm', '-n', str(obj)], capture_output=True, text=True, check=True).stdout.splitlines():
        p = line.split()
        if len(p) == 3 and p[1] in 'Tt' and p[2].startswith('_stub_'):
            syms.append((int(p[0], 16), p[2][6:]))
    text = bytearray()
    for line in subprocess.run(['otool', '-t', str(obj)], capture_output=True, text=True, check=True).stdout.splitlines():
        p = line.split()
        if len(p) > 1 and re.fullmatch(r'[0-9a-f]{8}', p[0]):
            text += bytes(int(b, 16) for b in p[1:])
syms.sort()
code = {}
for i, (addr, name) in enumerate(syms):
    end = syms[i + 1][0] if i + 1 < len(syms) else len(text)
    body = bytes(text[addr:end])
    while body and body[-1] in (0x90, 0xcc) and len(body) > 1 and body[-2] == 0xc3:  # strip alignment padding after ret
        body = body[:-1]
    code[name] = body
missing = sorted(set(BINDINGS.values()) - set(code))
if missing:
    sys.exit('stubs missing from assembly: %s' % missing)
with open(out, 'w') as f:
    f.write('/* Generated by tools/gen_native_stubs.py from native_stubs.s -- do not edit. */\n')
    for name in sorted(code):
        f.write('static const uint8_t lp32_stub_%s[] = {%s};\n' % (name, ','.join('0x%02x' % b for b in code[name])))
    f.write('\nstatic const struct lp32_native_stub {\n    const char *import_name;\n    const uint8_t *code;\n    size_t size;\n} lp32_native_stubs[] = {\n')
    for imp, stub in sorted(BINDINGS.items()):
        f.write('    {"%s", lp32_stub_%s, sizeof(lp32_stub_%s)},\n' % (imp, stub, stub))
    f.write('};\n')
print('%d stubs, %d bindings, %d bytes of code -> %s' % (len(code), len(BINDINGS), sum(len(c) for c in code.values()), out))
